apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-app.fullname" . }}-service
spec:
  selector:
    {{- include "nginx-app.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP


