apiVersion: ENC[AES256_GCM,data:lhU=,iv:eo6KH+B0qpdftEjGtgmck7+5lnsh9KK/4a4UB5dt5ug=,tag:vK+Wu+a4AOS5KoSp8RYiTw==,type:str]
data:
    password: ENC[AES256_GCM,data:Zf2NwKCqaQFA1PV9sQDDuA==,iv:uJTNAY78LNvyJ79W0/9Br7PmfmDxcP9aWdSwRWsoiCY=,tag:2k+PnvNtL/QFCpm1wBFtHg==,type:str]
    username: ENC[AES256_GCM,data:fE/x58z8Te+jRYn+,iv:V/LyB36HC3S44PxuR+wyvNN/KizpPhqMEE9Pvk2JdFA=,tag:fTvqbzrbaEvI1mASGRQAsw==,type:str]
kind: ENC[AES256_GCM,data:Cix9Dijs,iv:x+ifQcyCKY1C8HEm0YcP5pbmNZfozEXVpe4TcZtn3hw=,tag:ClolopKKQ91cellndO5TXA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:VDhhC3xw50o=,iv:N/seUHoRnsYXTwGb7U7AiajjLmQu+8pJsEXkBBNbPys=,tag:KAWC9+rWbyragIrVZn3gpA==,type:str]
    namespace: ENC[AES256_GCM,data:sacMzOSonw==,iv:JmGEtcKE0m5J3g6rdbKkP+CnovUorSU2h3KBagd3eUI=,tag:Gt2LM05SGms8kA3xjzESKA==,type:str]
type: ENC[AES256_GCM,data:+cpV4nBl,iv:fCQluoshJFGTxTBh/X/IXswVf7J4oEH3KzgWOvtM9to=,tag:Gc6NJ8sQFcba70R5ppYqXQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1aelsjdt2udnurpxelryl9pznxa974fu7xrjm0wu8s07wve40gsass2vkcj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrV1pKNG1zZ2p3UE9EQzBG
            aDdDcDJWWDl6QkNuNnp6Z1laZTV5R2xyRlRNCit0RE95L213M2lPQ1VuVXdqWUpu
            ZG9xa3BpOHRkUFpqSk9TejNRZ29rdmsKLS0tIGNLVm9HbXlBYzBLbUJSalNvN0VI
            M2xMa3B2K0VFbXdCckRvVHFVVkhsRkEKwfEDQcxYX/m261gKVhTK9A5ncQFPFl/z
            jvK0XUnz3GAZllUE8DZFOgjYWJJpW3njd//inSNVKRGOQIN8hnouYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-29T00:31:46Z"
    mac: ENC[AES256_GCM,data:Ff+QNTri7wXgL4V87zMKrSjHzg8YWrIK4IsQC0RgpieTrruGacpN/wbvkVjQ8F2YKdgpT1jl6l7bY6Phjoe6HPvOdQMu8Tq53+RU/BjFIzhw9vCQXX39udtrJwzCm0/BYGYfan44eoN9cq7BEryo/sRWDSn/b4OirXpb2iOCewY=,iv:IjY/0+AICPxDbE2Hxqt2BFh/Jkk1coVMsEaOyvHDscQ=,tag:CXdI/Sl5/yrsltzavZNw6g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
